package main

var OtherCities = map[string][]string{
	"ae": {"abu_dhabi", "ajman", "al_ain_city", "dubai", "ras_al_khaimah", "sharjah"},
	"al": {"tirana"},
	"am": {"yerevan"},
	"ao": {"luanda"},
	"ar": {"avellaneda", "bahia_blanca", "berazategui", "buenos_aires", "caseros", "catamarca", "comodoro_rivadavia", "cordoba", "corrientes", "florencio_varela", "formosa", "hurlingham", "isidro_casanova", "ituzaingo", "jose_c_paz", "jose_maria_ezeiza", "la_plata", "la_rioja", "laferrere", "lanus", "lomas_de_zamora", "mar_del_plata", "mendoza", "merlo", "monte_grande", "moreno", "moron", "neuquen", "parana", "pilar", "posadas", "quilmes", "resistencia", "rio_cuarto", "rio_gallegos", "rosario", "salta", "san_fernando", "san_juan", "san_justo", "san_luis", "san_miguel", "san_miguel_de_tucuman", "san_salvador_de_jujuy", "santa_fe", "villa_ballester"},
	"at": {"graz", "vienna"},
	"au": {"adelaide", "brisbane", "melbourne", "perth", "sydney"},
	"az": {"baku"},
	"ba": {"banja_luka", "sarajevo", "tuzla"},
	"bb": {"bridgetown"},
	"bd": {"chittagong", "dhaka", "rajshahi"},
	"be": {"antwerp", "brussels", "ghent", "liege"},
	"bg": {"burgas", "plovdiv", "rousse", "sofia", "stara_zagora", "varna"},
	"bh": {"manama"},
	"bn": {"bandar_seri_begawan"},
	"bo": {"cochabamba", "la_paz", "santa_cruz"},
	"br": {"aguas_lindas_de_goias", "alvorada", "americana", "ananindeua", "anapolis", "angra_dos_reis", "aparecida_de_goiania", "aracaju", "aracatuba", "araguaina", "arapiraca", "araraquara", "atibaia", "balneario_camboriu", "barra_mansa", "barueri", "bauru", "belem", "belford_roxo", "belo_horizonte", "betim", "blumenau", "boa_vista", "botucatu", "braganca_paulista", "brasilia", "cabo_frio", "cachoeiro_de_itapemirim", "camacari", "camaragibe", "campina_grande", "campinas", "campo_grande", "campo_largo", "campos_dos_goytacazes", "canoas", "caraguatatuba", "carapicuiba", "cariacica", "caruaru", "cascavel", "castanhal", "catalao", "catanduva", "caucaia", "caxias_do_sul", "chapeco", "colombo", "contagem", "cotia", "criciuma", "cuiaba", "curitiba", "diadema", "divinopolis", "dourados", "duque_de_caxias", "embu", "fazenda_rio_grande", "feira_de_santana", "florianopolis", "fortaleza", "foz_do_iguacu", "franca", "francisco_morato", "franco_da_rocha", "garanhuns", "goiania", "governador_valadares", "gravatai", "guarapuava", "guaratingueta", "guaruja", "guarulhos", "hortolandia", "imperatriz", "indaiatuba", "ipatinga", "itaborai", "itabuna", "itajai", "itanhaem", "itapevi", "itaquaquecetuba", "jaboatao_dos_guararapes", "jacarei", "jaragua_do_sul", "jau", "joao_monlevade", "joao_pessoa", "joinville", "juazeiro_do_norte", "juiz_de_fora", "jundiai", "lages", "limeira", "linhares", "londrina", "luziania", "macae", "macapa", "maceio", "mage", "manaus", "maraba", "maracanau", "marica", "marilia", "maringa", "maua", "mogi_das_cruzes", "montes_claros", "mossoro", "natal", "nilopolis", "niteroi", "nova_friburgo", "nova_iguacu", "novo_hamburgo", "olinda", "osasco", "ourinhos", "palhoca", "palmas", "paranagua", "parauapebas", "parnaiba", "parnamirim", "passo_fundo", "patos_de_minas", "paulista", "pelotas", "petrolina", "petropolis", "pindamonhangaba", "piracicaba", "pocos_de_caldas", "ponta_grossa", "porto_alegre", "porto_seguro", "porto_velho", "pouso_alegre", "praia_grande", "presidente_prudente", "queimados", "recife", "ribeirao_das_neves", "ribeirao_preto", "rio_branco", "rio_claro", "rio_de_janeiro", "rio_do_sul", "rio_grande", "rondonopolis", "salvador", "santa_cruz_do_sul", "santa_luzia", "santa_maria", "santarem", "santo_andre", "santos", "sao_bernardo_do_campo", "sao_carlos", "sao_goncalo", "sao_joao_de_meriti", "sao_jose", "sao_jose_do_rio_preto", "sao_jose_dos_campos", "sao_jose_dos_pinhais", "sao_leopoldo", "sao_luis", "sao_paulo", "sao_vicente", "serra", "sete_lagoas", "sinop", "sobral", "sorocaba", "sumare", "suzano", "taboao_da_serra", "tatui", "taubate", "teixeira_de_freitas", "teresina", "tubarao", "uberaba", "uberlandia", "valinhos", "valparaiso_de_goias", "varginha", "varzea_paulista", "viamao", "vila_velha", "vitoria", "vitoria_da_conquista", "vitoria_de_santo_antao", "volta_redonda"},
	"bs": {"nassau"},
	"bw": {"gaborone"},
	"by": {"brest", "gomel", "hrodna", "minsk"},
	"ca": {"brampton", "burnaby", "calgary", "edmonton", "gatineau", "hamilton", "kitchener", "laval", "longueuil", "mississauga", "montreal", "ottawa", "quebec", "regina", "saskatoon", "scarborough", "surrey", "toronto", "vancouver", "victoria", "windsor", "winnipeg"},
	"ch": {"bern", "geneva", "lausanne", "zurich"},
	"ci": {"abidjan"},
	"cl": {"antofagasta", "arica", "concepcion", "iquique", "la_serena", "port_montt", "rancagua", "santiago", "talca", "temuco", "valparaiso", "vina_del_mar"},
	"cn": {"guangzhou", "shanghai", "shenzhen"},
	"co": {"barranquilla", "bogota", "bucaramanga", "cartagena", "chia", "cucuta", "ibague", "manizales", "medellin", "neiva", "pasto", "pereira", "popayan", "santa_marta", "santiago_de_cali", "tunja", "valledupar", "villavicencio"},
	"cr": {"alajuela", "heredia", "san_jose"},
	"cu": {"havana"},
	"cw": {"willemstad"},
	"cy": {"limassol", "nicosia"},
	"cz": {"brno", "olomouc", "ostrava", "prague"},
	"de": {"bochum", "bremen", "cologne", "dortmund", "dresden", "duisburg", "dusseldorf", "essen", "frankfurt_am_main", "hamburg", "hanover", "karlsruhe", "leipzig", "mannheim", "munich", "nuremberg", "stuttgart", "wuppertal"},
	"dk": {"copenhagen"},
	"dm": {"roseau"},
	"do": {"santiago_de_los_caballeros", "santo_domingo", "santo_domingo_este"},
	"dz": {"algiers", "batna_city", "bejaia", "blida", "constantine", "djelfa", "oran", "setif", "skikda", "tlemcen"},
	"ec": {"ambato", "cuenca", "guayaquil", "loja", "machala", "portoviejo", "quito"},
	"ee": {"tallinn"},
	"eg": {"al_mansurah", "alexandria", "asyut", "cairo", "damietta", "giza", "ismailia", "port_said", "tanta", "zagazig"},
	"es": {"a_coruna", "alicante", "barcelona", "bilbao", "gijon", "granada", "las_palmas_de_gran_canaria", "madrid", "malaga", "murcia", "palma", "santa_cruz_de_tenerife", "seville", "terrassa", "valencia", "valladolid", "vigo", "zaragoza"},
	"et": {"addis_ababa"},
	"fi": {"espoo", "helsinki", "tampere"},
	"fr": {"angers", "bordeaux", "le_mans", "lille", "lyon", "marseille", "montpellier", "nantes", "nice", "paris", "rennes", "rouen", "strasbourg", "toulouse"},
	"ga": {"libreville"},
	"gb": {"belfast", "birmingham", "bradford", "bristol", "cardiff", "coventry", "croydon", "derby", "edinburgh", "glasgow", "hackney", "hull", "ilford", "islington", "leeds", "leicester", "liverpool", "manchester", "milton_keynes", "newcastle_upon_tyne", "northampton", "norwich", "nottingham", "plymouth", "reading", "sheffield", "slough", "southampton", "southwark", "stoke_on_trent", "wolverhampton"},
	"ge": {"batumi", "kutaisi", "tbilisi"},
	"gh": {"accra"},
	"gr": {"athens", "thessaloniki"},
	"gt": {"guatemala_city"},
	"gy": {"georgetown"},
	"hk": {"central"},
	"hn": {"san_pedro_sula", "tegucigalpa"},
	"hr": {"split", "zagreb"},
	"ht": {"port_au_prince"},
	"hu": {"budapest", "debrecen", "kecskemet", "miskolc", "pecs", "szeged", "szekesfehervar"},
	"id": {"balikpapan", "bandar_lampung", "bandung", "banjarmasin", "batam", "bekasi", "bogor", "cirebon", "denpasar", "depok", "jakarta", "jember", "kediri", "magelang", "makassar", "malang", "manado", "medan", "palembang", "pekanbaru", "pontianak", "samarinda", "semarang", "sidoarjo", "south_tangerang", "surabaya", "surakarta", "tangerang", "tasikmalaya", "yogyakarta"},
	"ie": {"dublin"},
	"il": {"haifa", "holon", "jerusalem", "petah_tikva", "ramat_gan", "rishon_letsiyyon", "tel_aviv"},
	"in": {"ahmedabad", "aizawl", "bengaluru", "bhopal", "bhubaneswar", "chandigarh", "chennai", "coimbatore", "dehradun", "delhi", "ghaziabad", "gurugram", "guwahati", "hyderabad", "indore", "jaipur", "jodhpur", "kanpur", "karnal", "kochi", "kolkata", "kollam", "kozhikode", "lucknow", "ludhiana", "malappuram", "meerut", "mohali", "mumbai", "nagpur", "navi_mumbai", "new_delhi", "noida", "palakkad", "patna", "pune", "raipur", "rajkot", "ranchi", "sagar", "shimla", "sikar", "surat", "thane", "thiruvananthapuram", "thrissur", "vadodara", "varanasi", "vijayawada", "visakhapatnam"},
	"iq": {"baghdad", "erbil"},
	"ir": {"tehran"},
	"is": {"reykjavik"},
	"it": {"bari", "bologna", "brescia", "cagliari", "catania", "florence", "genoa", "milan", "naples", "padova", "palermo", "pescara", "rome", "turin", "verona"},
	"jm": {"kingston", "montego_bay"},
	"jo": {"amman"},
	"jp": {"tokyo", "umeda", "yokohama"},
	"ke": {"nairobi"},
	"kg": {"bishkek"},
	"kh": {"phnom_penh"},
	"kr": {"buk_gu", "gangnam_gu", "goyang_si", "gwanak_gu", "incheon", "seo_gu", "seongnam_si", "seoul", "suwon", "yongin_si"},
	"kw": {"kuwait_city"},
	"kz": {"almaty", "astana"},
	"la": {"vientiane"},
	"lb": {"beirut"},
	"lc": {"castries"},
	"lk": {"colombo"},
	"lt": {"kaunas", "klaipeda", "siauliai", "vilnius"},
	"lu": {"luxembourg"},
	"lv": {"riga"},
	"ma": {"agadir", "beni_mellal", "casablanca", "el_jadida", "fes", "kenitra", "marrakesh", "meknes", "oujda", "rabat", "sale", "tangier", "tetouan"},
	"md": {"chisinau"},
	"me": {"podgorica"},
	"mg": {"antananarivo"},
	"mk": {"skopje"},
	"mm": {"yangon"},
	"mn": {"ulan_bator"},
	"mo": {"macao"},
	"mu": {"port_louis"},
	"mv": {"male"},
	"mx": {
		"acapulco_de_juarez",
		"aguascalientes",
		"apodaca",
		"azcapotzalco",
		"campeche",
		"centro",
		"chihuahua_city",
		"ciudad_juarez",
		"ciudad_nezahualcoyotl",
		"ciudad_obregon",
		"cuautitlan_izcalli",
		"cuernavaca",
		"culiacan",
		"durango",
		"ecatepec",
		"ensenada",
		"guadalajara",
		"guadalupe",
		"gustavo_adolfo_madero",
		"hermosillo",
		"iztapalapa",
		"juarez",
		"leon",
		"mazatlan",
		"merida",
		"mexicali",
		"mexico_city",
		"monterrey",
		"morelia",
		"naucalpan",
		"nogales",
		"oaxaca_city",
		"pachuca",
		"puebla_city",
		"queretaro_city",
		"reynosa",
		"saltillo",
		"san_luis_potosi_city",
		"tampico",
		"tepic",
		"tijuana",
		"tlalnepantla",
		"tlaxcala_city",
		"toluca",
		"torreon",
		"tuxtla_gutierrez",
		"venustiano_carranza",
		"veracruz",
		"xalapa",
		"zapopan",
	},
	"my": {
		"george_town",
		"ipoh",
		"johor_bahru",
		"kota_kinabalu",
		"kuala_lumpur",
		"kuching",
		"petaling_jaya",
		"puchong_batu_dua_belas",
		"shah_alam",
	},
	"mz": {"maputo"},
	"na": {"windhoek"},
	"ng": {"abuja", "katsina", "lagos", "port_harcourt"},
	"ni": {"managua"},
	"nl": {"almere_stad", "amsterdam", "naaldwijk", "rotterdam", "the_hague"},
	"no": {"oslo"},
	"np": {"bharatpur", "biratnagar", "ilam", "kaski", "kathmandu", "patan"},
	"nz": {"auckland", "christchurch", "hamilton", "wellington"},
	"om": {"muscat"},
	"pa": {"panama_city"},
	"pe": {
		"arequipa", "chiclayo", "chimbote", "cusco", "huancayo", "huanuco",
		"ica", "lima", "piura", "pucallpa", "tacna", "trujillo",
	},
	"ph": {
		"angeles_city", "antipolo_city", "bacolod_city", "bacoor", "baguio_city",
		"batangas", "butuan", "cabanatuan_city", "cabuyao", "cagayan_de_oro",
		"calamba", "caloocan_city", "carmona", "cebu_city", "city_of_muntinlupa",
		"dagupan", "dasmarinas", "davao_city", "general_trias", "iligan",
		"iloilo_city", "imus", "lahug", "las_pinas", "lipa_city", "lucena_city",
		"mabalacat", "makati_city", "malabon", "mandaluyong_city", "manila",
		"marikina_city", "naga", "nasugbu", "olongapo_city", "paranaque_city",
		"quezon_city", "san_jose_del_monte", "san_pablo_city", "san_pedro",
		"santa_rosa", "taguig", "talavera", "tanza", "tarlac_city", "tuguegarao_city",
		"urdaneta", "zamboanga_city",
	},
	"pk": {
		"faisalabad", "gujranwala", "islamabad", "karachi", "lahore",
		"multan", "muzaffargarh", "peshawar", "rawalpindi",
	},
	"pl": {
		"bialystok", "bydgoszcz", "gdansk", "gdynia", "gliwice",
		"katowice", "kielce", "krakow", "lodz", "lublin", "olsztyn",
		"poznan", "rzeszow", "szczecin", "warsaw", "wroclaw", "zabrze",
		"zielona_gora",
	},
	"pr": {"san_juan"},
	"pt": {
		"almada", "amadora", "braga", "coimbra", "funchal", "lisbon",
		"porto", "setubal", "vila_nova_de_gaia",
	},
	"py": {"asuncion", "ciudad_del_este"},
	"qa": {"doha"},
	"ro": {
		"arad", "brasov", "bucharest", "cluj_napoca", "constanta",
		"craiova", "galati", "iasi", "oradea", "pitesti", "ploiesti",
		"sibiu", "timisoara",
	},
	"rs": {"belgrade", "nis", "novi_sad"},
	"ru": {
		"chelyabinsk", "kazan", "krasnodar", "nizhniy_novgorod",
		"novosibirsk", "perm", "rostov_on_don", "samara", "st_petersburg",
		"ufa", "voronezh", "yekaterinburg",
	},
	"rw": {"kigali"},
	"sa": {"al_qatif", "dammam", "jeddah", "medina", "riyadh"},
	"se": {"gothenburg", "malmo", "stockholm"},
	"si": {"ljubljana", "maribor"},
	"sk": {"bratislava", "kosice", "nitra"},
	"sn": {"dakar"},
	"sr": {"paramaribo"},
	"sv": {"san_salvador"},
	"tg": {"lome"},
	"th": {"bangkok", "chiang_mai", "khon_kaen"},
	"tn": {"aryanah", "bizerte", "sfax", "sousse", "tunis"},
	"tr": {
		"adana", "adapazari", "afyonkarahisar", "aksaray", "amasya", "ankara",
		"antakya", "antalya", "atakum", "aydin", "balikesir", "batman",
		"bilecik", "bolu", "bursa", "corum", "denizli", "diyarbakir", "duezce",
		"edirne", "elazig", "erzurum", "eskisehir", "gaziantep", "giresun",
		"isparta", "istanbul", "kahramanmaras", "karabuk", "kastamonu",
		"kayseri", "kirklareli", "konya", "kosekoy", "kutahya",
		"magnesia_ad_sipylum", "mardin", "merkez", "mersin", "mugla",
		"nevsehir", "ordu", "osmaniye", "rize", "samsun", "sanliurfa",
		"sivas", "tekirdag", "tokat_province", "trabzon", "usak", "van",
		"yalova", "zonguldak",
	},
	"tt": {"chaguanas", "port_of_spain"},
	"tw": {
		"chang_hua", "hsinchu", "kaohsiung_city", "new_taipei", "taichung",
		"tainan_city", "taipei", "taoyuan_district", "zhongli_district",
	},
	"tz": {"dar_es_salaam"},
	"ua": {
		"cherkasy", "chernivtsi", "dnipro", "kharkiv", "khmelnytskyi", "kryvyi_rih",
		"kyiv", "lviv", "mykolayiv", "odesa", "poltava", "ternopil", "vinnytsia",
		"zaporizhzhya",
	},
	"ug": {"kampala"},
	"us": {
		"akron", "albany", "albuquerque", "alexandria", "arlington", "athens", "atlanta",
		"auburn", "aurora", "austin", "bakersfield", "baltimore", "baton_rouge", "birmingham",
		"bloomington", "boise", "boston", "brooklyn", "buffalo", "canton", "chandler", "charleston",
		"charlotte", "cincinnati", "cleveland", "colorado_springs", "columbia", "columbus", "concord",
		"dallas", "dayton", "decatur", "denver", "detroit", "el_paso", "fayetteville", "fontana",
		"fort_lauderdale", "fort_wayne", "fort_worth", "fredericksburg", "fresno", "gainesville",
		"glendale", "grand_rapids", "greensboro", "greenville", "henderson", "hialeah", "hollywood",
		"honolulu", "indianapolis", "irvine", "jackson", "jacksonville", "kansas_city", "katy",
		"kissimmee", "knoxville", "lafayette", "lake_worth", "lakeland", "lancaster", "las_vegas",
		"lawrenceville", "lexington", "lincoln", "long_beach", "louisville", "madison", "marietta",
		"memphis", "mesa", "milwaukee", "minneapolis", "monroe", "montgomery", "naples", "nashville",
		"new_orleans", "newark", "oakland", "oklahoma_city", "omaha", "orlando", "peoria", "philadelphia",
		"phoenix", "pittsburgh", "plano", "portland", "providence", "queens", "raleigh", "reno",
		"richmond", "riverside", "rochester", "sacramento", "saint_paul", "salt_lake_city", "san_antonio",
		"san_diego", "san_francisco", "san_jose", "seattle", "silver_spring", "spokane", "spring",
		"springfield", "st_louis", "staten_island", "stockton", "tacoma", "tallahassee", "tampa",
		"tappahannock", "the_bronx", "tucson", "tulsa", "vancouver", "virginia_beach", "washington",
		"west_palm_beach", "wichita", "wilmington", "woodbridge",
	},
	"uy": {"maldonado", "montevideo"},
	"uz": {"bukhara", "samarkand", "tashkent"},
	"ve": {"barquisimeto", "caracas", "ciudad_guayana", "maracaibo", "maracay", "valencia"},
	"vn": {"bien_hoa", "can_tho", "da_nang", "haiphong", "hanoi", "ho_chi_minh_city", "nha_trang"},
	"xk": {"pristina"},
	"ye": {"sanaa"},
	"za": {"bloemfontein", "boksburg", "cape_town", "centurion", "durban", "johannesburg", "port_elizabeth", "pretoria"},
	"zm": {"lusaka"},
	"zw": {"harare"},
}
